version: "3.7"
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        - USER=${CONTAINER_USER:-root}
        - USER_ID=${CONTAINER_USER_ID:-0}
        - GROUP=${CONTAINER_GROUP:-root}
        - GROUP_ID=${CONTAINER_GROUP_ID:-0}
    env_file: .env
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - stamp_log_data:/tmp
    command: sh -c "/app/logger.sh && bundle && bundle exec ruby app.rb -o 0.0.0.0 -p 3333"
    ports:
      - "${SINATRA_PORT:-3333}:3333"
volumes:
  bundle_data:
  stamp_log_data:
    external: true # docker volume create stamp_log_data
